theme: jekyll-theme-dinky
title: Ellie's EAE Portfolio
description: contains my work as a student
git init
git add .
git commit -m "First commit"
git branch -M master
git remote add origin https://github.com/T31K/Portfolio-Site.git
git push -u origin master
